(define (domain construction)
  (:requirements :strips :equality)
  (:predicates
    (Node ?n)
    (Element ?e)
    (Printed ?e)
    (Removed ?e)
    (Traj ?t)
    (PrintAction ?n ?e ?t)
    (Collision ?t ?e)
    (Grounded ?n)
    (Edge ?n1 ?e ?n2)
    (Supports ?e ?n)
    (Stiff)
  )

  (:action print
    :parameters (?n ?e ?t)
    :precondition (and (PrintAction ?n ?e ?t) (Printed ?e) ; (Stiff)
                       (forall (?e2) (imply (Supports ?e2 ?n) (Printed ?e2)))
                       (forall (?e2) (imply (Collision ?t ?e2) (Removed ?e2)))
                  )
    :effect (and (Removed ?e)
                 (not (Printed ?e)))
  )
)